### PR TITLE
Validate contact form

### PR DESCRIPTION
**Pull request by vechicin**
We created the JavaScript necessary to validate the email input in the contact form.

### CODE REVIEW

**Review by bini-i — APPROVED** [review]
# Status: Approved :heavy_check_mark:          
### Hello @vechicin and @williamrolando88  :wave: 

**Congratulations**, your project meets all the requirements and it is **approved** :tada:.

#### To highlight
- Correct use of Github flow and there are no linter errors .
- Commit messages are written well and shows good collaboration.
- Very good implementing more than one functional input validations using the specified design and they all work as intended.

Keep up the good work :100: 

#### If you have any questions feel free to ask within the PR thread.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Code Reviewer)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

**Comment by carlos-ssh** [comment]
# 🚫⚠️🛑 INVALID SUBMISSION 🚫⚠️🛑
Hi @vechicin , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, **that submitted a merged pull request link**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jorgevrgs** [comment]
> # 🚫⚠️🛑 INVALID SUBMISSION 🚫⚠️🛑
> Hi @vechicin ,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, **that submitted a merged pull request link**
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Dear @carlos-ssh 

This is a coding-partner activity. The code was checked and approved by the first reviewer. This is the reason why the PR was merged.

**Review by rotimiazeez — COMMENTED** [review]
# Hi @vechicin 👋, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
